'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.1433
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.1433.
'
Namespace Entradas
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="entradasSoap", [Namespace]:="http://gateway/inacapi/entradas"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BD))>  _
    Partial Public Class entradas
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CabezalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProductoDespachoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LotesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProgramaFaenaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BoletoCompraVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CabezalBoletoCompraVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PalletsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProductoDesosadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DestinoDesosadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegTypeDesosadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegTypeDespachoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Dominio.My.MySettings.Default.Dominio_Entradas_entradas
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CabezalCompleted As CabezalCompletedEventHandler
        
        '''<remarks/>
        Public Event ProductoDespachoCompleted As ProductoDespachoCompletedEventHandler
        
        '''<remarks/>
        Public Event LotesCompleted As LotesCompletedEventHandler
        
        '''<remarks/>
        Public Event ProgramaFaenaCompleted As ProgramaFaenaCompletedEventHandler
        
        '''<remarks/>
        Public Event BoletoCompraVentaCompleted As BoletoCompraVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event CabezalBoletoCompraVentaCompleted As CabezalBoletoCompraVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event PalletsCompleted As PalletsCompletedEventHandler
        
        '''<remarks/>
        Public Event ProductoDesosadoCompleted As ProductoDesosadoCompletedEventHandler
        
        '''<remarks/>
        Public Event DestinoDesosadoCompleted As DestinoDesosadoCompletedEventHandler
        
        '''<remarks/>
        Public Event RegTypeDesosadoCompleted As RegTypeDesosadoCompletedEventHandler
        
        '''<remarks/>
        Public Event RegTypeDespachoCompleted As RegTypeDespachoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/Cabezal", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cabezal(<System.Xml.Serialization.XmlElementAttribute("Tropa")> ByVal Tropa() As CabezalTropa) As Integer
            Dim results() As Object = Me.Invoke("Cabezal", New Object() {Tropa})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CabezalAsync(ByVal Tropa() As CabezalTropa)
            Me.CabezalAsync(Tropa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CabezalAsync(ByVal Tropa() As CabezalTropa, ByVal userState As Object)
            If (Me.CabezalOperationCompleted Is Nothing) Then
                Me.CabezalOperationCompleted = AddressOf Me.OnCabezalOperationCompleted
            End If
            Me.InvokeAsync("Cabezal", New Object() {Tropa}, Me.CabezalOperationCompleted, userState)
        End Sub
        
        Private Sub OnCabezalOperationCompleted(ByVal arg As Object)
            If (Not (Me.CabezalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CabezalCompleted(Me, New CabezalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/ProductoDespacho", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProductoDespacho(<System.Xml.Serialization.XmlElementAttribute("Producto")> ByVal Producto() As ProductosDespacho) As Integer
            Dim results() As Object = Me.Invoke("ProductoDespacho", New Object() {Producto})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProductoDespachoAsync(ByVal Producto() As ProductosDespacho)
            Me.ProductoDespachoAsync(Producto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProductoDespachoAsync(ByVal Producto() As ProductosDespacho, ByVal userState As Object)
            If (Me.ProductoDespachoOperationCompleted Is Nothing) Then
                Me.ProductoDespachoOperationCompleted = AddressOf Me.OnProductoDespachoOperationCompleted
            End If
            Me.InvokeAsync("ProductoDespacho", New Object() {Producto}, Me.ProductoDespachoOperationCompleted, userState)
        End Sub
        
        Private Sub OnProductoDespachoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProductoDespachoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProductoDespachoCompleted(Me, New ProductoDespachoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/Lotes", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Lotes(<System.Xml.Serialization.XmlElementAttribute("Tropa")> ByVal Tropa() As LotesTropa) As Integer
            Dim results() As Object = Me.Invoke("Lotes", New Object() {Tropa})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LotesAsync(ByVal Tropa() As LotesTropa)
            Me.LotesAsync(Tropa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LotesAsync(ByVal Tropa() As LotesTropa, ByVal userState As Object)
            If (Me.LotesOperationCompleted Is Nothing) Then
                Me.LotesOperationCompleted = AddressOf Me.OnLotesOperationCompleted
            End If
            Me.InvokeAsync("Lotes", New Object() {Tropa}, Me.LotesOperationCompleted, userState)
        End Sub
        
        Private Sub OnLotesOperationCompleted(ByVal arg As Object)
            If (Not (Me.LotesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LotesCompleted(Me, New LotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/ProgramaFaenas", RequestElementName:="ProgramaFaenas", RequestNamespace:="http://gateway/inacapi/entradas", ResponseElementName:="ProgramaFaenasResponse", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProgramaFaena(<System.Xml.Serialization.XmlElementAttribute("Programa")> ByVal Programa() As ProgramaFaena) As <System.Xml.Serialization.XmlElementAttribute("ProgramaFaenasResult")> Integer
            Dim results() As Object = Me.Invoke("ProgramaFaena", New Object() {Programa})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProgramaFaenaAsync(ByVal Programa() As ProgramaFaena)
            Me.ProgramaFaenaAsync(Programa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProgramaFaenaAsync(ByVal Programa() As ProgramaFaena, ByVal userState As Object)
            If (Me.ProgramaFaenaOperationCompleted Is Nothing) Then
                Me.ProgramaFaenaOperationCompleted = AddressOf Me.OnProgramaFaenaOperationCompleted
            End If
            Me.InvokeAsync("ProgramaFaena", New Object() {Programa}, Me.ProgramaFaenaOperationCompleted, userState)
        End Sub
        
        Private Sub OnProgramaFaenaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProgramaFaenaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProgramaFaenaCompleted(Me, New ProgramaFaenaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/BoletoCompraVentas", RequestElementName:="BoletoCompraVentas", RequestNamespace:="http://gateway/inacapi/entradas", ResponseElementName:="BoletoCompraVentasResponse", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BoletoCompraVenta(<System.Xml.Serialization.XmlElementAttribute("Tropa")> ByVal Tropa() As BoletoCompraVenta) As <System.Xml.Serialization.XmlElementAttribute("BoletoCompraVentasResult")> Integer
            Dim results() As Object = Me.Invoke("BoletoCompraVenta", New Object() {Tropa})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BoletoCompraVentaAsync(ByVal Tropa() As BoletoCompraVenta)
            Me.BoletoCompraVentaAsync(Tropa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BoletoCompraVentaAsync(ByVal Tropa() As BoletoCompraVenta, ByVal userState As Object)
            If (Me.BoletoCompraVentaOperationCompleted Is Nothing) Then
                Me.BoletoCompraVentaOperationCompleted = AddressOf Me.OnBoletoCompraVentaOperationCompleted
            End If
            Me.InvokeAsync("BoletoCompraVenta", New Object() {Tropa}, Me.BoletoCompraVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnBoletoCompraVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.BoletoCompraVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BoletoCompraVentaCompleted(Me, New BoletoCompraVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/CabezalBoletoCompraVenta", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CabezalBoletoCompraVenta(<System.Xml.Serialization.XmlElementAttribute("TropaBoleto")> ByVal TropaBoleto() As CabezalBoletoCompraVenta) As Integer
            Dim results() As Object = Me.Invoke("CabezalBoletoCompraVenta", New Object() {TropaBoleto})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CabezalBoletoCompraVentaAsync(ByVal TropaBoleto() As CabezalBoletoCompraVenta)
            Me.CabezalBoletoCompraVentaAsync(TropaBoleto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CabezalBoletoCompraVentaAsync(ByVal TropaBoleto() As CabezalBoletoCompraVenta, ByVal userState As Object)
            If (Me.CabezalBoletoCompraVentaOperationCompleted Is Nothing) Then
                Me.CabezalBoletoCompraVentaOperationCompleted = AddressOf Me.OnCabezalBoletoCompraVentaOperationCompleted
            End If
            Me.InvokeAsync("CabezalBoletoCompraVenta", New Object() {TropaBoleto}, Me.CabezalBoletoCompraVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnCabezalBoletoCompraVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.CabezalBoletoCompraVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CabezalBoletoCompraVentaCompleted(Me, New CabezalBoletoCompraVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/Pallets", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Pallets(<System.Xml.Serialization.XmlElementAttribute("Pallet")> ByVal Pallet() As Pallet) As Integer
            Dim results() As Object = Me.Invoke("Pallets", New Object() {Pallet})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PalletsAsync(ByVal Pallet() As Pallet)
            Me.PalletsAsync(Pallet, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PalletsAsync(ByVal Pallet() As Pallet, ByVal userState As Object)
            If (Me.PalletsOperationCompleted Is Nothing) Then
                Me.PalletsOperationCompleted = AddressOf Me.OnPalletsOperationCompleted
            End If
            Me.InvokeAsync("Pallets", New Object() {Pallet}, Me.PalletsOperationCompleted, userState)
        End Sub
        
        Private Sub OnPalletsOperationCompleted(ByVal arg As Object)
            If (Not (Me.PalletsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PalletsCompleted(Me, New PalletsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/ProductoDesosado", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProductoDesosado(<System.Xml.Serialization.XmlElementAttribute("Producto")> ByVal Producto() As ProductoDesosado) As Integer
            Dim results() As Object = Me.Invoke("ProductoDesosado", New Object() {Producto})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProductoDesosadoAsync(ByVal Producto() As ProductoDesosado)
            Me.ProductoDesosadoAsync(Producto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProductoDesosadoAsync(ByVal Producto() As ProductoDesosado, ByVal userState As Object)
            If (Me.ProductoDesosadoOperationCompleted Is Nothing) Then
                Me.ProductoDesosadoOperationCompleted = AddressOf Me.OnProductoDesosadoOperationCompleted
            End If
            Me.InvokeAsync("ProductoDesosado", New Object() {Producto}, Me.ProductoDesosadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnProductoDesosadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProductoDesosadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProductoDesosadoCompleted(Me, New ProductoDesosadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/DestinoDesosado", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DestinoDesosado(<System.Xml.Serialization.XmlElementAttribute("Destino")> ByVal Destino() As DestinoDesosado) As Integer
            Dim results() As Object = Me.Invoke("DestinoDesosado", New Object() {Destino})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DestinoDesosadoAsync(ByVal Destino() As DestinoDesosado)
            Me.DestinoDesosadoAsync(Destino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DestinoDesosadoAsync(ByVal Destino() As DestinoDesosado, ByVal userState As Object)
            If (Me.DestinoDesosadoOperationCompleted Is Nothing) Then
                Me.DestinoDesosadoOperationCompleted = AddressOf Me.OnDestinoDesosadoOperationCompleted
            End If
            Me.InvokeAsync("DestinoDesosado", New Object() {Destino}, Me.DestinoDesosadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDestinoDesosadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DestinoDesosadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DestinoDesosadoCompleted(Me, New DestinoDesosadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/RegTypeDesosado", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegTypeDesosado(<System.Xml.Serialization.XmlElementAttribute("RegTypeDes")> ByVal RegTypeDes() As RegTypeDesosado) As Integer
            Dim results() As Object = Me.Invoke("RegTypeDesosado", New Object() {RegTypeDes})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegTypeDesosadoAsync(ByVal RegTypeDes() As RegTypeDesosado)
            Me.RegTypeDesosadoAsync(RegTypeDes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegTypeDesosadoAsync(ByVal RegTypeDes() As RegTypeDesosado, ByVal userState As Object)
            If (Me.RegTypeDesosadoOperationCompleted Is Nothing) Then
                Me.RegTypeDesosadoOperationCompleted = AddressOf Me.OnRegTypeDesosadoOperationCompleted
            End If
            Me.InvokeAsync("RegTypeDesosado", New Object() {RegTypeDes}, Me.RegTypeDesosadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegTypeDesosadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegTypeDesosadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegTypeDesosadoCompleted(Me, New RegTypeDesosadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway/inacapi/entradas/RegTypeDespacho", RequestNamespace:="http://gateway/inacapi/entradas", ResponseNamespace:="http://gateway/inacapi/entradas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegTypeDespacho(<System.Xml.Serialization.XmlElementAttribute("RegTypeDespa")> ByVal RegTypeDespa() As RegTypeDespacho) As Integer
            Dim results() As Object = Me.Invoke("RegTypeDespacho", New Object() {RegTypeDespa})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegTypeDespachoAsync(ByVal RegTypeDespa() As RegTypeDespacho)
            Me.RegTypeDespachoAsync(RegTypeDespa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegTypeDespachoAsync(ByVal RegTypeDespa() As RegTypeDespacho, ByVal userState As Object)
            If (Me.RegTypeDespachoOperationCompleted Is Nothing) Then
                Me.RegTypeDespachoOperationCompleted = AddressOf Me.OnRegTypeDespachoOperationCompleted
            End If
            Me.InvokeAsync("RegTypeDespacho", New Object() {RegTypeDespa}, Me.RegTypeDespachoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegTypeDespachoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegTypeDespachoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegTypeDespachoCompleted(Me, New RegTypeDespachoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class CabezalTropa
        Inherits BD
        
        Private fechaRecepcionField As String
        
        Private animalCodigoField As Integer
        
        Private tropaNoField As Integer
        
        Private tropaDescField As String
        
        Private dicoseCodigoField As String
        
        Private faenaTipoField As Integer
        
        Private productorDicoseField As String
        
        Private productorRUCField As Long
        
        Private productorNombreField As String
        
        Private productorDepartamentoField As Integer
        
        Private consignatarioCodigoField As Integer
        
        Private consignatarioDicoseCodigoField As String
        
        Private consignatarioNombreField As String
        
        Private consignatarioDepartamentoField As Integer
        
        Private tercerosCodigoField As Integer
        
        Private tercerosRUCField As Long
        
        Private tercerosNombreField As String
        
        Private tercerosDepartamentoField As Integer
        
        Private monedaCodigoField As Integer
        
        Private monedaFleteField As Integer
        
        Private fleteCargoField As Integer
        
        Private valorFleteField As Decimal
        
        Private pagoModoField As Integer
        
        Private pagoDiasField As Integer
        
        Private pagoTipoField As Integer
        
        Private transportesField() As Transporte
        
        Private guiasField() As Guia
        
        '''<comentarios/>
        Public Property FechaRecepcion() As String
            Get
                Return Me.fechaRecepcionField
            End Get
            Set
                Me.fechaRecepcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AnimalCodigo() As Integer
            Get
                Return Me.animalCodigoField
            End Get
            Set
                Me.animalCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TropaNo() As Integer
            Get
                Return Me.tropaNoField
            End Get
            Set
                Me.tropaNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TropaDesc() As String
            Get
                Return Me.tropaDescField
            End Get
            Set
                Me.tropaDescField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DicoseCodigo() As String
            Get
                Return Me.dicoseCodigoField
            End Get
            Set
                Me.dicoseCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FaenaTipo() As Integer
            Get
                Return Me.faenaTipoField
            End Get
            Set
                Me.faenaTipoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductorDicose() As String
            Get
                Return Me.productorDicoseField
            End Get
            Set
                Me.productorDicoseField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductorRUC() As Long
            Get
                Return Me.productorRUCField
            End Get
            Set
                Me.productorRUCField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductorNombre() As String
            Get
                Return Me.productorNombreField
            End Get
            Set
                Me.productorNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductorDepartamento() As Integer
            Get
                Return Me.productorDepartamentoField
            End Get
            Set
                Me.productorDepartamentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ConsignatarioCodigo() As Integer
            Get
                Return Me.consignatarioCodigoField
            End Get
            Set
                Me.consignatarioCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ConsignatarioDicoseCodigo() As String
            Get
                Return Me.consignatarioDicoseCodigoField
            End Get
            Set
                Me.consignatarioDicoseCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ConsignatarioNombre() As String
            Get
                Return Me.consignatarioNombreField
            End Get
            Set
                Me.consignatarioNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ConsignatarioDepartamento() As Integer
            Get
                Return Me.consignatarioDepartamentoField
            End Get
            Set
                Me.consignatarioDepartamentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosCodigo() As Integer
            Get
                Return Me.tercerosCodigoField
            End Get
            Set
                Me.tercerosCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosRUC() As Long
            Get
                Return Me.tercerosRUCField
            End Get
            Set
                Me.tercerosRUCField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosNombre() As String
            Get
                Return Me.tercerosNombreField
            End Get
            Set
                Me.tercerosNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosDepartamento() As Integer
            Get
                Return Me.tercerosDepartamentoField
            End Get
            Set
                Me.tercerosDepartamentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MonedaCodigo() As Integer
            Get
                Return Me.monedaCodigoField
            End Get
            Set
                Me.monedaCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MonedaFlete() As Integer
            Get
                Return Me.monedaFleteField
            End Get
            Set
                Me.monedaFleteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FleteCargo() As Integer
            Get
                Return Me.fleteCargoField
            End Get
            Set
                Me.fleteCargoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ValorFlete() As Decimal
            Get
                Return Me.valorFleteField
            End Get
            Set
                Me.valorFleteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoModo() As Integer
            Get
                Return Me.pagoModoField
            End Get
            Set
                Me.pagoModoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoDias() As Integer
            Get
                Return Me.pagoDiasField
            End Get
            Set
                Me.pagoDiasField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoTipo() As Integer
            Get
                Return Me.pagoTipoField
            End Get
            Set
                Me.pagoTipoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Transportes() As Transporte()
            Get
                Return Me.transportesField
            End Get
            Set
                Me.transportesField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Guias() As Guia()
            Get
                Return Me.guiasField
            End Get
            Set
                Me.guiasField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Transporte
        Inherits BD
        
        Private transporteCodigoField As Integer
        
        Private transporteRUCField As Long
        
        Private transporteNombreField As String
        
        Private transporteDepartamentoField As Integer
        
        '''<comentarios/>
        Public Property TransporteCodigo() As Integer
            Get
                Return Me.transporteCodigoField
            End Get
            Set
                Me.transporteCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TransporteRUC() As Long
            Get
                Return Me.transporteRUCField
            End Get
            Set
                Me.transporteRUCField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TransporteNombre() As String
            Get
                Return Me.transporteNombreField
            End Get
            Set
                Me.transporteNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TransporteDepartamento() As Integer
            Get
                Return Me.transporteDepartamentoField
            End Get
            Set
                Me.transporteDepartamentoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(RegTypeDespacho)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(RegTypeDesosado)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DestinoDesosado)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ProductoDesosado)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PalletCaja)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Pallet)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CabezalBoletoCompraVenta)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Renglon)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BoletoCompraVenta)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Grupo)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ProgramaFaena)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Lote)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(LotesTropa)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ProductosDespacho)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Guia)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Transporte)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CabezalTropa)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class BD
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class RegTypeDespacho
        Inherits BD
        
        Private dotNoField As Integer
        
        Private regTypeField As Integer
        
        '''<comentarios/>
        Public Property DotNo() As Integer
            Get
                Return Me.dotNoField
            End Get
            Set
                Me.dotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RegType() As Integer
            Get
                Return Me.regTypeField
            End Get
            Set
                Me.regTypeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class RegTypeDesosado
        Inherits BD
        
        Private dotNoField As Integer
        
        Private regTypeField As Integer
        
        '''<comentarios/>
        Public Property DotNo() As Integer
            Get
                Return Me.dotNoField
            End Get
            Set
                Me.dotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RegType() As Integer
            Get
                Return Me.regTypeField
            End Get
            Set
                Me.regTypeField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class DestinoDesosado
        Inherits BD
        
        Private dotNoField As Integer
        
        Private destinoCodigoField As Integer
        
        '''<comentarios/>
        Public Property DotNo() As Integer
            Get
                Return Me.dotNoField
            End Get
            Set
                Me.dotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DestinoCodigo() As Integer
            Get
                Return Me.destinoCodigoField
            End Get
            Set
                Me.destinoCodigoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class ProductoDesosado
        Inherits BD
        
        Private dotNoField As Integer
        
        Private productoCodigoField As Integer
        
        Private noPiecesField As Integer
        
        Private prevDotNoField As Integer
        
        Private prevDotNo1Field As Integer
        
        Private prevDotNo2Field As Integer
        
        Private prevDotNo3Field As Integer
        
        Private prevDotNo4Field As Integer
        
        Private prevDotNo5Field As Integer
        
        Private prevDotNo6Field As Integer
        
        Private prevDotNo7Field As Integer
        
        Private prevDotNo8Field As Integer
        
        Private prevDotNo9Field As Integer
        
        Private prevDotNo10Field As Integer
        
        Private prevDotNo11Field As Integer
        
        '''<comentarios/>
        Public Property DotNo() As Integer
            Get
                Return Me.dotNoField
            End Get
            Set
                Me.dotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductoCodigo() As Integer
            Get
                Return Me.productoCodigoField
            End Get
            Set
                Me.productoCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NoPieces() As Integer
            Get
                Return Me.noPiecesField
            End Get
            Set
                Me.noPiecesField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo() As Integer
            Get
                Return Me.prevDotNoField
            End Get
            Set
                Me.prevDotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo1() As Integer
            Get
                Return Me.prevDotNo1Field
            End Get
            Set
                Me.prevDotNo1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo2() As Integer
            Get
                Return Me.prevDotNo2Field
            End Get
            Set
                Me.prevDotNo2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo3() As Integer
            Get
                Return Me.prevDotNo3Field
            End Get
            Set
                Me.prevDotNo3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo4() As Integer
            Get
                Return Me.prevDotNo4Field
            End Get
            Set
                Me.prevDotNo4Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo5() As Integer
            Get
                Return Me.prevDotNo5Field
            End Get
            Set
                Me.prevDotNo5Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo6() As Integer
            Get
                Return Me.prevDotNo6Field
            End Get
            Set
                Me.prevDotNo6Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo7() As Integer
            Get
                Return Me.prevDotNo7Field
            End Get
            Set
                Me.prevDotNo7Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo8() As Integer
            Get
                Return Me.prevDotNo8Field
            End Get
            Set
                Me.prevDotNo8Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo9() As Integer
            Get
                Return Me.prevDotNo9Field
            End Get
            Set
                Me.prevDotNo9Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo10() As Integer
            Get
                Return Me.prevDotNo10Field
            End Get
            Set
                Me.prevDotNo10Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PrevDotNo11() As Integer
            Get
                Return Me.prevDotNo11Field
            End Get
            Set
                Me.prevDotNo11Field = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class PalletCaja
        Inherits BD
        
        Private boxNoField As Integer
        
        '''<comentarios/>
        Public Property BoxNo() As Integer
            Get
                Return Me.boxNoField
            End Get
            Set
                Me.boxNoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Pallet
        Inherits BD
        
        Private palletNoField As Integer
        
        Private palletStatusField As Integer
        
        Private productCodeField As Integer
        
        Private cajasField() As PalletCaja
        
        '''<comentarios/>
        Public Property PalletNo() As Integer
            Get
                Return Me.palletNoField
            End Get
            Set
                Me.palletNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PalletStatus() As Integer
            Get
                Return Me.palletStatusField
            End Get
            Set
                Me.palletStatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductCode() As Integer
            Get
                Return Me.productCodeField
            End Get
            Set
                Me.productCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Caja")>  _
        Public Property Cajas() As PalletCaja()
            Get
                Return Me.cajasField
            End Get
            Set
                Me.cajasField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class CabezalBoletoCompraVenta
        Inherits BD
        
        Private tropaNoField As Integer
        
        Private purchaseStatusField As Integer
        
        Private tipoFaenaField As Integer
        
        Private tercerosCodigoField As Integer
        
        Private tercerosRUCField As Long
        
        Private tercerosNombreField As String
        
        Private tercerosDepartamentoField As Integer
        
        Private cargoFleteField As Integer
        
        Private monedaFleteField As Integer
        
        Private valorFleteField As Decimal
        
        Private monedaCodigoField As Integer
        
        Private pagoModoField As Integer
        
        Private pagoDiasField As Integer
        
        Private numeroBoletoField As String
        
        Private fechaBoletoField As Date
        
        '''<comentarios/>
        Public Property TropaNo() As Integer
            Get
                Return Me.tropaNoField
            End Get
            Set
                Me.tropaNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PurchaseStatus() As Integer
            Get
                Return Me.purchaseStatusField
            End Get
            Set
                Me.purchaseStatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TipoFaena() As Integer
            Get
                Return Me.tipoFaenaField
            End Get
            Set
                Me.tipoFaenaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosCodigo() As Integer
            Get
                Return Me.tercerosCodigoField
            End Get
            Set
                Me.tercerosCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosRUC() As Long
            Get
                Return Me.tercerosRUCField
            End Get
            Set
                Me.tercerosRUCField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosNombre() As String
            Get
                Return Me.tercerosNombreField
            End Get
            Set
                Me.tercerosNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TercerosDepartamento() As Integer
            Get
                Return Me.tercerosDepartamentoField
            End Get
            Set
                Me.tercerosDepartamentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CargoFlete() As Integer
            Get
                Return Me.cargoFleteField
            End Get
            Set
                Me.cargoFleteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MonedaFlete() As Integer
            Get
                Return Me.monedaFleteField
            End Get
            Set
                Me.monedaFleteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ValorFlete() As Decimal
            Get
                Return Me.valorFleteField
            End Get
            Set
                Me.valorFleteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MonedaCodigo() As Integer
            Get
                Return Me.monedaCodigoField
            End Get
            Set
                Me.monedaCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoModo() As Integer
            Get
                Return Me.pagoModoField
            End Get
            Set
                Me.pagoModoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoDias() As Integer
            Get
                Return Me.pagoDiasField
            End Get
            Set
                Me.pagoDiasField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroBoleto() As String
            Get
                Return Me.numeroBoletoField
            End Get
            Set
                Me.numeroBoletoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaBoleto() As Date
            Get
                Return Me.fechaBoletoField
            End Get
            Set
                Me.fechaBoletoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Renglon
        Inherits BD
        
        Private animalBatchNoField As Integer
        
        Private subCategCodeField As Integer
        
        Private priceKgField As Decimal
        
        Private scaleKg_1Field As Decimal
        
        Private scaleKg_2Field As Decimal
        
        Private scaleKg_3Field As Decimal
        
        Private breedTypeField As Integer
        
        Private criPayField As Integer
        
        Private payTypeField As Integer
        
        Private descripcionField As String
        
        Private cantidadField As Integer
        
        Private conformationField As Integer
        
        '''<comentarios/>
        Public Property AnimalBatchNo() As Integer
            Get
                Return Me.animalBatchNoField
            End Get
            Set
                Me.animalBatchNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SubCategCode() As Integer
            Get
                Return Me.subCategCodeField
            End Get
            Set
                Me.subCategCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PriceKg() As Decimal
            Get
                Return Me.priceKgField
            End Get
            Set
                Me.priceKgField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ScaleKg_1() As Decimal
            Get
                Return Me.scaleKg_1Field
            End Get
            Set
                Me.scaleKg_1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ScaleKg_2() As Decimal
            Get
                Return Me.scaleKg_2Field
            End Get
            Set
                Me.scaleKg_2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ScaleKg_3() As Decimal
            Get
                Return Me.scaleKg_3Field
            End Get
            Set
                Me.scaleKg_3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property BreedType() As Integer
            Get
                Return Me.breedTypeField
            End Get
            Set
                Me.breedTypeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CriPay() As Integer
            Get
                Return Me.criPayField
            End Get
            Set
                Me.criPayField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PayType() As Integer
            Get
                Return Me.payTypeField
            End Get
            Set
                Me.payTypeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Integer
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Conformation() As Integer
            Get
                Return Me.conformationField
            End Get
            Set
                Me.conformationField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class BoletoCompraVenta
        Inherits BD
        
        Private tropaNoField As Integer
        
        Private renglonesField() As Renglon
        
        '''<comentarios/>
        Public Property TropaNo() As Integer
            Get
                Return Me.tropaNoField
            End Get
            Set
                Me.tropaNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Renglones() As Renglon()
            Get
                Return Me.renglonesField
            End Get
            Set
                Me.renglonesField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Grupo
        Inherits BD
        
        Private secuenciaField As Integer
        
        Private tropaNoField As Integer
        
        Private loteNoField As Integer
        
        Private cantidadField As Integer
        
        '''<comentarios/>
        Public Property Secuencia() As Integer
            Get
                Return Me.secuenciaField
            End Get
            Set
                Me.secuenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TropaNo() As Integer
            Get
                Return Me.tropaNoField
            End Get
            Set
                Me.tropaNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LoteNo() As Integer
            Get
                Return Me.loteNoField
            End Get
            Set
                Me.loteNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Cantidad() As Integer
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class ProgramaFaena
        Inherits BD
        
        Private fechaFaenaField As String
        
        Private gruposField() As Grupo
        
        '''<comentarios/>
        Public Property FechaFaena() As String
            Get
                Return Me.fechaFaenaField
            End Get
            Set
                Me.fechaFaenaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Grupos() As Grupo()
            Get
                Return Me.gruposField
            End Get
            Set
                Me.gruposField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Lote
        Inherits BD
        
        Private loteNoField As Integer
        
        Private categoriaCodigoField As Integer
        
        Private razaCodigoField As Integer
        
        Private vivosField As Integer
        
        Private muertosField As Integer
        
        Private rechazadosField As Integer
        
        Private muertosEnProcesoField As Integer
        
        Private descripcionField As String
        
        Private tipoFaenaField As Integer
        
        '''<comentarios/>
        Public Property LoteNo() As Integer
            Get
                Return Me.loteNoField
            End Get
            Set
                Me.loteNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CategoriaCodigo() As Integer
            Get
                Return Me.categoriaCodigoField
            End Get
            Set
                Me.categoriaCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RazaCodigo() As Integer
            Get
                Return Me.razaCodigoField
            End Get
            Set
                Me.razaCodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Vivos() As Integer
            Get
                Return Me.vivosField
            End Get
            Set
                Me.vivosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Muertos() As Integer
            Get
                Return Me.muertosField
            End Get
            Set
                Me.muertosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Rechazados() As Integer
            Get
                Return Me.rechazadosField
            End Get
            Set
                Me.rechazadosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MuertosEnProceso() As Integer
            Get
                Return Me.muertosEnProcesoField
            End Get
            Set
                Me.muertosEnProcesoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TipoFaena() As Integer
            Get
                Return Me.tipoFaenaField
            End Get
            Set
                Me.tipoFaenaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class LotesTropa
        Inherits BD
        
        Private tropaNoField As Integer
        
        Private lotesField() As Lote
        
        '''<comentarios/>
        Public Property TropaNo() As Integer
            Get
                Return Me.tropaNoField
            End Get
            Set
                Me.tropaNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Lotes() As Lote()
            Get
                Return Me.lotesField
            End Get
            Set
                Me.lotesField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class ProductosDespacho
        Inherits BD
        
        Private dotNoField As Integer
        
        Private productoCodigoField As Integer
        
        '''<comentarios/>
        Public Property DotNo() As Integer
            Get
                Return Me.dotNoField
            End Get
            Set
                Me.dotNoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ProductoCodigo() As Integer
            Get
                Return Me.productoCodigoField
            End Get
            Set
                Me.productoCodigoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://gateway/inacapi/entradas")>  _
    Partial Public Class Guia
        Inherits BD
        
        Private serieField As String
        
        Private dicoseGuiaNoField As Integer
        
        '''<comentarios/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DicoseGuiaNo() As Integer
            Get
                Return Me.dicoseGuiaNoField
            End Get
            Set
                Me.dicoseGuiaNoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub CabezalCompletedEventHandler(ByVal sender As Object, ByVal e As CabezalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CabezalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ProductoDespachoCompletedEventHandler(ByVal sender As Object, ByVal e As ProductoDespachoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProductoDespachoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub LotesCompletedEventHandler(ByVal sender As Object, ByVal e As LotesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LotesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ProgramaFaenaCompletedEventHandler(ByVal sender As Object, ByVal e As ProgramaFaenaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProgramaFaenaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub BoletoCompraVentaCompletedEventHandler(ByVal sender As Object, ByVal e As BoletoCompraVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BoletoCompraVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub CabezalBoletoCompraVentaCompletedEventHandler(ByVal sender As Object, ByVal e As CabezalBoletoCompraVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CabezalBoletoCompraVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub PalletsCompletedEventHandler(ByVal sender As Object, ByVal e As PalletsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PalletsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ProductoDesosadoCompletedEventHandler(ByVal sender As Object, ByVal e As ProductoDesosadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProductoDesosadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub DestinoDesosadoCompletedEventHandler(ByVal sender As Object, ByVal e As DestinoDesosadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DestinoDesosadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub RegTypeDesosadoCompletedEventHandler(ByVal sender As Object, ByVal e As RegTypeDesosadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegTypeDesosadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub RegTypeDespachoCompletedEventHandler(ByVal sender As Object, ByVal e As RegTypeDespachoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegTypeDespachoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
